name: email_inmemory
description: An in-memory implementation of the EmailClient interface, suitable for testing and development environments.
repository: https://github.com/flutter-news-app-full-source-code/email-inmemory
publish_to: none
version: 1.0.1

environment:
  sdk: ^3.9.0

dependencies: 
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: v1.3.1
  email_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/email-client.git
      ref: v1.0.1
  logging: ^1.3.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^9.0.0
