name: email_inmemory
description: An in-memory implementation of the EmailClient interface, suitable for testing and development environments.
repository: https://github.com/flutter-news-app-full-source-code/email-inmemory
publish_to: none

environment:
  sdk: ^3.8.0

dependencies: 
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
  email_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/email-client.git
  logging: ^1.3.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^9.0.0
