name: ht_email_inmemory
description: An in-memory implementation of the HtEmailClient interface, suitable for testing and development environments.
repository: https://github.com/headlines-toolkit/ht-email-inmemory
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  ht_email_client:
    git:
      url: https://github.com/headlines-toolkit/ht-email-client.git
  ht_shared:
    git:
      url: https://github.com/headlines-toolkit/ht-shared.git

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^8.0.0
